const teamsData = [
  { team_name: 'Anaheim Ducks', location: 'Anaheim, CA', home_rink: 'Honda Center' },
  { team_name: 'Arizona Coyotes', location: 'Glendale, AZ', home_rink: 'Gila River Arena' },
  { team_name: 'Boston Bruins', location: 'Boston, MA', home_rink: 'TD Garden' },
  { team_name: 'Buffalo Sabres', location: 'Buffalo, NY', home_rink: 'KeyBank Center' },
  { team_name: 'Calgary Flames', location: 'Calgary, AB', home_rink: 'Scotiabank Saddledome' },
  { team_name: 'Carolina Hurricanes', location: 'Raleigh, NC', home_rink: 'PNC Arena' },
  { team_name: 'Chicago Blackhawks', location: 'Chicago, IL', home_rink: 'United Center' },
  { team_name: 'Colorado Avalanche', location: 'Denver, CO', home_rink: 'Pepsi Center' },
  { team_name: 'Columbus Blue Jackets', location: 'Columbus, OH', home_rink: 'Nationwide Arena' },
  { team_name: 'Dallas Stars', location: 'Dallas, TX', home_rink: 'American Airlines Center' },
  { team_name: 'Detroit Red Wings', location: 'Detroit, MI', home_rink: 'Little Ceasers Arena' },
  { team_name: 'Edmonton Oilers', location: 'Edmonton, CDN', home_rink: 'Rogers Place' },
  { team_name: 'Florida Panthers', location: 'Sunrise, FL', home_rink: 'BB&T Center' },
  { team_name: 'Los Angeles Kings', location: 'Los Angeles, CA', home_rink: 'STAPLES Center' },
  { team_name: 'Minnesota Wild', location: 'Saint Paul, MN', home_rink: 'Xcel Energy Center' },
  { team_name: 'Montreal Canadiens', location: 'Montreal, QC', home_rink: 'Centre Bell' },
  { team_name: 'Nashville Predators', location: 'Nashville, TN', home_rink: 'Bridgestone Arena' },
  { team_name: 'New Jersey Devils', location: 'Newark, NY', home_rink: 'Prudential Center' },
  { team_name: 'New York Islanders', location: 'New York, NY', home_rink: 'Barclays Center' },
  { team_name: 'New York Rangers', location: 'New York City, NY', home_rink: 'Madison Square Garden' },
  { team_name: 'Ottawa Senators', location: 'Ottawa, ON', home_rink: 'Canadian Tire Centre' },
  { team_name: 'Philadelphia Flyers', location: 'Philadelphia, PA', home_rink: 'Wells Fargo Center' },
  { team_name: 'Pittsburgh Penguins', location: 'Pittsburgh, PA', home_rink: 'PPG Paints Arena' },
  { team_name: 'San Jose Sharks', location: 'San Jose, CA', home_rink: 'SAP Center' },
  { team_name: 'St. Louis Blues', location: 'ST. Louis, MO', home_rink: 'Enterprise Center' },
  { team_name: 'Tampa Bay Lightning', location: 'Tampa, FL', home_rink: 'Amalie Arena' },
  { team_name: 'Toronto Maple Leafs', location: 'Toronto, CDN', home_rink: 'Scotiabank Arena' },
  { team_name: 'Vancouver Canucks', location: 'Vancouver, BC', home_rink: 'Rogers Arena' },
  { team_name: 'Vegas Golden Knights', location: 'Las Vegas, NV', home_rink: 'T-Mobile Arena' },
  { team_name: 'Washington Capitals', location: 'Washington, D.C.', home_rink: 'Capital One Arena' },
  { team_name: 'Winnipeg Jets', location: 'Winnipeg, CDN', home_rink: 'Bell MTS Place' }
];

module.exports = teamsData;