const teamsData = [
  { teamName: 'Anaheim Ducks', location: 'Anaheim, CA', homeRink: 'Honda Center' },
  { teamName: 'Arizona Coyotes', location: 'Glendale, AZ', homeRink: 'Gila River Arena' },
  { teamName: 'Boston Bruins', location: 'Boston, MA', homeRink: 'TD Garden' },
  { teamName: 'Buffalo Sabres', location: 'Buffalo, NY', homeRink: 'KeyBank Center' },
  { teamName: 'Calgary Flames', location: 'Calgary, AB', homeRink: 'Scotiabank Saddledome' },
  { teamName: 'Carolina Hurricanes', location: 'Raleigh, NC', homeRink: 'PNC Arena' },
  { teamName: 'Chicago Blackhawks', location: 'Chicago, IL', homeRink: 'United Center' },
  { teamName: 'Colorado Avalanche', location: 'Denver, CO', homeRink: 'Pepsi Center' },
  { teamName: 'Columbus Blue Jackets', location: 'Columbus, OH', homeRink: 'Nationwide Arena' },
  { teamName: 'Dallas Stars', location: 'Dallas, TX', homeRink: 'American Airlines Center' },
  { teamName: 'Detroit Red Wings', location: 'Detroit, MI', homeRink: 'Little Ceasers Arena' },
  { teamName: 'Edmonton Oilers', location: 'Edmonton, CDN', homeRink: 'Rogers Place' },
  { teamName: 'Florida Panthers', location: 'Sunrise, FL', homeRink: 'BB&T Center' },
  { teamName: 'Los Angeles Kings', location: 'Los Angeles, CA', homeRink: 'STAPLES Center' },
  { teamName: 'Minnesota Wild', location: 'Saint Paul, MN', homeRink: 'Xcel Energy Center' },
  { teamName: 'Montreal Canadiens', location: 'Montreal, QC', homeRink: 'Centre Bell' },
  { teamName: 'Nashville Predators', location: 'Nashville, TN', homeRink: 'Bridgestone Arena' },
  { teamName: 'New Jersey Devils', location: 'Newark, NY', homeRink: 'Prudential Center' },
  { teamName: 'New York Islanders', location: 'New York, NY', homeRink: 'Barclays Center' },
  { teamName: 'New York Rangers', location: 'New York City, NY', homeRink: 'Madison Square Garden' },
  { teamName: 'Ottawa Senators', location: 'Ottawa, ON', homeRink: 'Canadian Tire Centre' },
  { teamName: 'Philadelphia Flyers', location: 'Philadelphia, PA', homeRink: 'Wells Fargo Center' },
  { teamName: 'Pittsburgh Penguins', location: 'Pittsburgh, PA', homeRink: 'PPG Paints Arena' },
  { teamName: 'San Jose Sharks', location: 'San Jose, CA', homeRink: 'SAP Center' },
  { teamName: 'St. Louis Blues', location: 'ST. Louis, MO', homeRink: 'Enterprise Center' },
  { teamName: 'Tampa Bay Lightning', location: 'Tampa, FL', homeRink: 'Amalie Arena' },
  { teamName: 'Toronto Maple Leafs', location: 'Toronto, CDN', homeRink: 'Scotiabank Arena' },
  { teamName: 'Vancouver Canucks', location: 'Vancouver, BC', homeRink: 'Rogers Arena' },
  { teamName: 'Vegas Golden Knights', location: 'Las Vegas, NV', homeRink: 'T-Mobile Arena' },
  { teamName: 'Washington Capitals', location: 'Washington, D.C.', homeRink: 'Capital One Arena' },
  { teamName: 'Winnipeg Jets', location: 'Winnipeg, CDN', homeRink: 'Bell MTS Place' }
];

module.exports = teamsData;