const teamsData = [
  { teamName: 'Anaheim Ducks', acronym: 'ANA', loc: 'Anaheim, CA', homeRink: 'Honda Center' },
  { teamName: 'Arizona Coyotes', acronym: 'ARI', loc: 'Glendale, AZ', homeRink: 'Gila River Arena' },
  { teamName: 'Boston Bruins', acronym: 'BOS', loc: 'Boston, MA', homeRink: 'TD Garden' },
  { teamName: 'Buffalo Sabres', acronym: 'BUF', loc: 'Buffalo, NY', homeRink: 'KeyBank Center' },
  { teamName: 'Calgary Flames', acronym: 'CGY', loc: 'Calgary, AB', homeRink: 'Scotiabank Saddledome' },
  { teamName: 'Carolina Hurricanes', acronym: 'CAR', loc: 'Raleigh, NC', homeRink: 'PNC Arena' },
  { teamName: 'Chicago Blackhawks', acronym: 'CHI', loc: 'Chicago, IL', homeRink: 'United Center' },
  { teamName: 'Colorado Avalanche', acronym: 'COL', loc: 'Denver, CO', homeRink: 'Pepsi Center' },
  { teamName: 'Columbus Blue Jackets', acronym: 'CBJ', loc: 'Columbus, OH', homeRink: 'Nationwide Arena' },
  { teamName: 'Dallas Stars', acronym: 'DAL', loc: 'Dallas, TX', homeRink: 'American Airlines Center' },
  { teamName: 'Detroit Red Wings', acronym: 'DET', loc: 'Detroit, MI', homeRink: 'Little Ceasers Arena' },
  { teamName: 'Edmonton Oilers', acronym: 'EDM', loc: 'Edmonton, CDN', homeRink: 'Rogers Place' },
  { teamName: 'Florida Panthers', acronym: 'FLA', loc: 'Sunrise, FL', homeRink: 'BB&T Center' },
  { teamName: 'Los Angeles Kings', acronym: 'LAK', loc: 'Los Angeles, CA', homeRink: 'STAPLES Center' },
  { teamName: 'Minnesota Wild', acronym: 'MIN', loc: 'Saint Paul, MN', homeRink: 'Xcel Energy Center' },
  { teamName: 'Montreal Canadiens', acronym: 'MTL', loc: 'Montreal, QC', homeRink: 'Centre Bell' },
  { teamName: 'Nashville Predators', acronym: 'NSH', loc: 'Nashville, TN', homeRink: 'Bridgestone Arena' },
  { teamName: 'New Jersey Devils', acronym: 'NJD', loc: 'Newark, NY', homeRink: 'Prudential Center' },
  { teamName: 'New York Islanders', acronym: 'NYI', loc: 'New York, NY', homeRink: 'Barclays Center' },
  { teamName: 'New York Rangers', acronym: 'NYR', loc: 'New York City, NY', homeRink: 'Madison Square Garden' },
  { teamName: 'Ottawa Senators', acronym: 'OTT', loc: 'Ottawa, ON', homeRink: 'Canadian Tire Centre' },
  { teamName: 'Philadelphia Flyers', acronym: 'PHI', loc: 'Philadelphia, PA', homeRink: 'Wells Fargo Center' },
  { teamName: 'Pittsburgh Penguins', acronym: 'PIT', loc: 'Pittsburgh, PA', homeRink: 'PPG Paints Arena' },
  { teamName: 'San Jose Sharks', acronym: 'SJS', loc: 'San Jose, CA', homeRink: 'SAP Center' },
  { teamName: 'St. Louis Blues', acronym: 'STL', loc: 'ST. Louis, MO', homeRink: 'Enterprise Center' },
  { teamName: 'Tampa Bay Lightning', acronym: 'TBL', loc: 'Tampa, FL', homeRink: 'Amalie Arena' },
  { teamName: 'Toronto Maple Leafs', acronym: 'TOR', loc: 'Toronto, CDN', homeRink: 'Scotiabank Arena' },
  { teamName: 'Vancouver Canucks', acronym: 'VAN', loc: 'Vancouver, BC', homeRink: 'Rogers Arena' },
  { teamName: 'Vegas Golden Knights', acronym: 'VGK', loc: 'Las Vegas, NV', homeRink: 'T-Mobile Arena' },
  { teamName: 'Washington Capitals', acronym: 'WSH', loc: 'Washington, D.C.', homeRink: 'Capital One Arena' },
  { teamName: 'Winnipeg Jets', acronym: 'WPG', loc: 'Winnipeg, CDN', homeRink: 'Bell MTS Place' }
];

module.exports = teamsData;